### ISSUE TITLE
wsproto divergence

### ISSUE THREAD

**Issue by belm0** [HyperionGray/trio-websocket#14]
I'm concerned that trio-websocket is dependent on a fork of wsproto which includes two non-trivial PR's.  https://github.com/python-hyper/wsproto/pull/50 specifically doesn't appear to have buy-in yet from a project maintainer.

The consequence is that I'll need to make my own project dependent on this fork, and I'm not sure how long this situation will last, nor if the fork will be promptly updated with bug fixes etc. from upstream, nor if some patch might be added which isn't on par with the quality level of wsproto.

If it's at all reasonable to use wsproto as is while working to get the PR's in question resolved, I'd recommend that.

**Comment by belm0** [comment]
It seemed that trio-websocket was working sufficiently well without the wsproto PR's in question, so I'd like to understand more clearly what the necessity is.

**Comment by mehaase** [comment]
I share your concern. I was really struggling to correctly implement teardown of the WebSocket connection and the TCP connection without that upstream PR. More details here: https://github.com/python-hyper/wsproto/issues/64. I don't think the PR lacks buy-in as much as the right people haven't looked at it. There are three PRs open that over a year old, and one is an uncontroversial change to the API docs, so I fear that `wsproto` may be unmaintained.

Because `trio-websocket` lacks automated tests right now, I was testing the teardown code by carefully modifying the example server and client and looking at the packet capture in Wireshark. You may not notice these issues in sample code, but I suspect they will become serious problems in production code, particularly in long-lived servers that handle lots of incoming connections.

I think a reasonable approach to resolving this is to write some automated test cases to verify correct closing behavior, and then see if the implementation can be modified to work with upstream `wsproto`. And in parallel, maybe we can figure out who to ping to look at that PR and accept/reject it.

Thoughts?

**Comment by Kriechi** [comment]
@mehaase:
> to write some automated test cases to verify correct closing behavior

You mean in wsproto or trio-websocket?
I tried to implemented a full test in #50 to address precisely this - unless you spotted a missing edge case?

**Comment by mehaase** [comment]
@Kriechi I was referring to test cases for `trio-websocket`.
