### ISSUE TITLE
Naming confusion

### ISSUE THREAD

**Issue by belm0** [HyperionGray/trio-websocket#16]
> Trio WebSockets
> This project implements WebSockets for Trio and is based on the Sans-I/O wsproto project.

git and pypi paths are trio-websocket, but the project refers to itself and websockets in the plural.

Plural form seems more natural, and the other trio-websockets is willing to concede.  Painful, but do a rename now while the project only has one or two users?

**Comment by mehaase** [comment]
I picked the singular because the protocol itself is singular, i.e. Websocket RFC. This seems to be common. Of 37 packages on PyPI with websocket in the name[1], 34 use the singular form and 3 use the plural form. So I'm inclined to keep the singular form. The docs definitely need to be updated to use the language more carefully.

1. I used these commands to search for singular and plural websocket names: `pip3 search '*websocket*' | egrep -i '^[a-zA-Z-]+websockets' | wc -l` and `pip3 search '*websocket*' | egrep -i '^[a-zA-Z-]+websocket[^s]' | wc -l`
