### ISSUE TITLE
Use URLs in client API?

### ISSUE THREAD

**Issue by njsmith** [HyperionGray/trio-websocket#36]
Maybe instead of 

```python
async with open_websocket(host, port, resource, use_ssl) as ws:
    ...
```

it should be

```python
async with open_websocket("wss://host:port/resource") as ws:
    ...
```

?

There are a bunch of reasonable URL parsing libraries that would make this easy, maybe [hyperlink](https://hyperlink.readthedocs.io/en/stable/)?

**Comment by mehaase** [comment]
There is a URL convenience function on master right now:

```python
async with open_websocket_url('ws://foobar.com/baz?bat') as conn:
    pass
```

Is that what you're looking for? There is a blurb about it in the README, and real documentation is on my todo list.

One doubt in my mind about the current API is whether all of the public functions need to have `websocket` in the name. Should it be called `open_url()` instead of `open_websocket_url()`? And `open()` instead of `open_websocket()`? My favorite [asyncio WebSocket library](https://websockets.readthedocs.io/en/stable/) uses short names like `connect()` and `serve()`. I am leaning towards this style.

**Comment by mehaase** [comment]
@belm0 what do you think about this renaming:

> One doubt in my mind about the current API is whether all of the public functions need to have websocket in the name. Should it be called open_url() instead of open_websocket_url()? And open() instead of open_websocket()?

**Comment by belm0** [comment]
I think users would prefer the more qualified names so the can import the individual functions.

I.e. callsites in their code use open_websocket_url rather than trio_websocket.open_url.

**Comment by mehaase** [comment]
Ok, then I will keep the current naming scheme. I opened #57 to create API documentation, which should address Nathaniel's original post in this thread.
