### ISSUE TITLE
server should close the connection when the handler ends

### ISSUE THREAD

**Issue by miracle2k** [HyperionGray/trio-websocket#50]
Currently, if my connection handler function ends, the connection will remain open. For example:

```python
async def main():
    await serve_websocket(foo, '127.0.0.1', 9000, ssl_context=None);

async def foo(websocket):
    pass

trio.run(main)
```

I would expect my returning from this function to shut down the connection. Currently, it seems I have to call `await websocket.aclose` myself, which seems unnecessary.

**Comment by njsmith** [comment]
`serve_listeners` does close connections after the handler dies (rudely, using `trio.aclose_forcefully`). But i guess the issue here is that the connection's background task is hanging around and preventing that from happening? It should definitely shut down and clean up when the handler exits.

> `async for connection in serve_websocket(): ...`

This doesn't work so well if your server wants to handle two connections at the same time :-)

**Comment by miracle2k** [comment]
I guess that's right. My handler dies, but trio-websocket wraps it (https://github.com/HyperionGray/trio-websocket/blob/master/trio_websocket/__init__.py#L737), and has a reader task running as well; I suppose it's a question of shutting that down, then.

**Comment by belm0** [comment]
>> `async for connection in serve_websocket(): ...`

>This doesn't work so well if your server wants to handle two connections at the same time :-)

Well, there's:

```
async with trio.open_nursery() as nursery:
    async for connection in serve_websocket(...):
        nursery.start_soon(handle_connection, connection)
```

but indeed, this can't provide a automatic close signal to the listen loop either.  Never mind!
